### PR TITLE
fix panic under python3.12

### LINKED ISSUE #18: Can't build the qoi package with Python 3.12
Note numpy 1.26 is needed with Python 3.12 because distutils is removed.
```
Building wheels for collected packages: qoi
  Building wheel for qoi (pyproject.toml): started
  Building wheel for qoi (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for qoi (pyproject.toml) did not run successfully.
  exit code: 1

  [50 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-312
  creating build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\benchmark.py -> build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\_version.py -> build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\__init__.py -> build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\qoi.pxd -> build\lib.win-amd64-cpython-312\qoi
  running build_ext
  building 'qoi.qoi' extension
  creating build\temp.win-amd64-cpython-312
  creating build\temp.win-amd64-cpython-312\Release
  creating build\temp.win-amd64-cpython-312\Release\src
  creating build\temp.win-amd64-cpython-312\Release\src\qoi
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DQOI_MALLOC=PyMem_Malloc -DQOI_FREE=PyMem_Free -IC:\Users\Gudni\AppData\Local\Temp\pip-build-env-c92eykgi\overlay\Lib\site-packages\numpy\core\include -ID:\Prusa-Firmware-Buddy-Private\.venv\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/qoi/implementation.c /Fobuild\temp.win-amd64-cpython-312\Release\src/qoi/implementation.obj
  implementation.c
  C:\Users\Gudni\AppData\Local\Temp\pip-install-y6f4ym_p\qoi_7194dc5fc5904c6d98e093ad731ed32d\src\qoi\phoboslab_qoi/qoi.h(597): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  C:\Users\Gudni\AppData\Local\Temp\pip-install-y6f4ym_p\qoi_7194dc5fc5904c6d98e093ad731ed32d\src\qoi\phoboslab_qoi/qoi.h(641): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  C:\Users\Gudni\AppData\Local\Temp\pip-install-y6f4ym_p\qoi_7194dc5fc5904c6d98e093ad731ed32d\src\qoi\phoboslab_qoi/qoi.h(619): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DQOI_MALLOC=PyMem_Malloc -DQOI_FREE=PyMem_Free -IC:\Users\Gudni\AppData\Local\Temp\pip-build-env-c92eykgi\overlay\Lib\site-packages\numpy\core\include -ID:\Prusa-Firmware-Buddy-Private\.venv\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/qoi/qoi.c /Fobuild\temp.win-amd64-cpython-312\Release\src/qoi/qoi.obj
  qoi.c
  C:\Users\Gudni\AppData\Local\Temp\pip-build-env-c92eykgi\overlay\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  src/qoi/qoi.c(13239): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
  src/qoi/qoi.c(21985): error C2039: 'curexc_traceback': is not a member of '_ts'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
  src/qoi/qoi.c(21988): error C2039: 'curexc_traceback': is not a member of '_ts'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
  src/qoi/qoi.c(23336): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(24904): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(24959): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25100): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25155): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25296): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25351): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25530): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25585): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25936): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qoi
Failed to build qoi
ERROR: Could not build wheels for qoi, which is required to install pyproject.toml-based projects
```

### PR DESCRIPTION
**Pull request by synodriver**
fix #18

### CODE REVIEW

**Comment by synodriver** [comment]
@kodonnell Please try this patch, I tested it on windows and it works fine. @gudnimg Thanks for reporting such a serious bug!

**Comment by kodonnell** [comment]
Great stuff, works for me on 3.12.0 on linux = )

**Comment by kodonnell** [comment]
Happy for you to merge now if you want, though no harm waiting for the tests to run. If you want to add 3.12 support, as per the py312 branch (well, just the CI bits) even better! I've just added you as a collaborator 'cos I'm going to bed = )

**Comment by synodriver** [comment]
Thanks, let me have a try.

**Comment by synodriver** [comment]
Why does the macos CI takes so long to run? Emmm.. It's actually waiting?

**Pull request merged**
