### PR TITLE
Prepare for Cython 3.0

### PR DESCRIPTION
**Pull request by synodriver**
Cython have released their latest version 3.0 with many bugs fixed and new features. Now compatibility warning at compile time is gone. And this patch update bundled qoi to the latest version.

### CODE REVIEW

**Comment by synodriver** [comment]
Should we restrict Cython dependence in requirements.txt to ```Cython>=3.0.0```?

**Comment by kodonnell** [comment]
Cool! I'm happy if we restrict to Cython>=3.0.0 for now if the tests all pass - if anyone raises an issue we can look into it then.

**Comment by synodriver** [comment]
I build it locally and it works fine.

**Comment by synodriver** [comment]
It's strange that macos fails to build. Unluckly I didn't have a mac. Besides, the logs is not available neither... Would like to get some help if someone is using macos.

**Comment by synodriver** [comment]
Great!

**Comment by kodonnell** [comment]
No worries - sorry I forgot to merge it! Looks like some issues with 3.12 but I'll see if I can fix that now.

**Pull request merged**
