### PR TITLE
Bump python version

### PR DESCRIPTION
**Pull request by synodriver**
Python 3.7 reached its End of Life (EOL) a few months ago, so it's time to say goodbye.

https://devguide.python.org/versions/

### CODE REVIEW

**Comment by synodriver** [comment]
And a new release should be uploaded once CI is done.

**Comment by gudnimg** [comment]
Strange, `setuptools==59.6.0` seems to coincide with the last release to support Python 3.7 🤔

https://setuptools.pypa.io/en/stable/history.html

**Comment by gudnimg** [comment]
I think I found it. https://github.com/pypa/cibuildwheel/blob/461bed51d3619c4c670f008148de8ce1465ba586/cibuildwheel/resources/constraints-python38.txt#L31

We need to update `pypa/cibuildwheel@v2.3.1` in the workflow https://github.com/kodonnell/qoi/blob/main/.github/workflows/wheels.yml 

The latest version 2.16.2 seems to support Python 3.8 to 3.12 👍 https://github.com/pypa/cibuildwheel/tree/v2.16.2/cibuildwheel/resources

**Comment by kodonnell** [comment]
Thanks!

**Pull request merged**
